'use client'
// import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

//import boostrap
import "@fortawesome/fontawesome-free/css/all.min.css"
import "bootstrap-css-only/css/bootstrap.min.css"
// import "mdbreact/dist/css/mdb.css"
import app from "@/style/app.module.scss"
import { Container } from 'react-bootstrap'
import AppHeader from '@/components/public/app.header'
import AppFooter from '@/components/public/app.footer'
//boostrap


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" >
      <body className={inter.className}>
        <AppHeader />
        <Container>
          {children}
        </Container>
        <AppFooter />
      </body>
    </html >
  )
}
